# Aethel Linux network configuration
#
# interface = interface name
# dhcp = yes|no
# ip = ip/mask       (static only)
# gateway = ip       (static only)
# dns = ip           (static only)

interface = eth0
dhcp = yes
